package com.fincons.parkingsystem.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fincons.parkingsystem.entity.SlotStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Data Transfer Object for ParkingSlot entities.
 * This class is used to transfer parking slot data between different layers of the application.
 * It provides a simplified representation of a parking slot, suitable for client-facing responses.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ParkingSlotDto {
    /**
     * The unique identifier for the parking slot.
     * This is typically generated by the database.
     */
    private Long id;
    /**
     * A unique number or identifier for the slot within its parking lot.
     * This helps in locating the slot physically.
     */
    private String slotNumber;
    /**
     * The current status of the parking slot, such as AVAILABLE or OCCUPIED.
     * This is an enumerated type, defined in the SlotStatus enum.
     */
    private SlotStatus status;
    /**
     * The identifier of the parking lot to which this slot belongs.
     * This is a foreign key relationship to the ParkingLot entity.
     */
    private Long parkingLotId;
}
