package com.fincons.parkingsystem.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.*;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Data Transfer Object for ParkingLot entities.
 * This class is used to transfer parking lot data between different layers of the application.
 * It includes validation constraints to ensure that the data is valid before processing.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ParkingLotDto {
    /**
     * The unique identifier for the parking lot.
     * This is typically generated by the database.
     */
    private Long id;
    /**
     * The name of the parking lot.
     * This field is mandatory and cannot be blank.
     */
    @NotBlank(message = "Parking lot name cannot be empty.")
    private String name;
    /**
     * The physical location of the parking lot.
     * This field is optional.
     */

    private String location;
    /**
     * The total number of parking slots in the lot.
     * This field is mandatory and must be at least 1.
     */
    @NotNull(message = "Total slots cannot be null.")
    @Min(value = 1, message = "Total slots must be at least 1.")
    @Max(value=50,message = "Total slots cannot be more than 70")
    private Integer totalSlots;
    /**
     * The base price per hour for parking in this lot.
     * This field is mandatory and must be a non-negative value.
     */
    @NotNull(message = "Base price per hour cannot be null.")
    @Min(value = 0, message = "Base price per hour must be a positive value.")
    @Max(value=1000,message = "Base price per hour cannot be more than 1000")
    private Double basePricePerHour;
    /**
     * The timestamp when the parking lot was created.
     * This is typically set by the system.
     */
    private LocalDateTime createdAt;
    /**
     * A list of Data Transfer Objects for the parking slots within this lot.
     * This is used to display details of all slots in the parking lot.
     */
    private List<ParkingSlotDto> parkingSlots;


}
