package com.fincons.parkingsystem.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fincons.parkingsystem.entity.ParkingSessionStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Data Transfer Object for ParkingSession entities.
 * This class is used to transfer parking session data, including calculated charges and other details,
 * between the service layer and the client. It provides a comprehensive view of a parking session.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ParkingSessionDto
{
    /**
     * The unique identifier for the parking session.
     * This is typically generated by the database.
     */
    private Long id;
    /**
     * The registration number of the vehicle associated with this session.
     */
    private String vehicleNumber;
    /**
     * The identifier of the parking slot occupied during this session.
     */
    private Long parkingSlotId;

    /**
     * The name of the parking lot where the slot is located.
     * This provides additional context for the session.
     */
    private String parkingLotName;
    /**
     * The timestamp when the vehicle entered the parking lot.
     */
    private LocalDateTime entryTime;
    /**
     * The timestamp when the vehicle exited the parking lot.
     * This is null for active sessions.
     */
    private LocalDateTime exitTime;
    /**
     * The total amount charged for the parking session.
     * This is calculated upon exit.
     */
    private Double totalAmount;

    /**
     * The base price per hour at the time of the vehicle's exit.
     * This is used in the charge calculation.
     */
    private Double basePricePerHour;

    /**
     * The total number of hours for which the user was charged.
     * This is calculated based on the duration of the stay.
     */
    private Long hoursCharged;

    /**
     * The occupancy percentage of the parking lot at the time of the vehicle's exit.
     * This can influence the pricing.
     */
    private Double occupancyPercentage;
    /**
     * The pricing multiplier applied to the base price, based on occupancy.
     * Higher occupancy may result in a higher multiplier.
     */
    private Double multiplier;
    /**
     * The current status of the parking session, such as ACTIVE or COMPLETED.
     * This is an enumerated type, defined in the ParkingSessionStatus enum.
     */
    private ParkingSessionStatus status;
}
