package com.fincons.parkingsystem.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fincons.parkingsystem.entity.VehicleType;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Data Transfer Object for Vehicle entities.
 * This class is used to transfer vehicle data between different layers of the application,
 * such as from the service layer to the controller or vice versa.
 * It includes validation constraints to ensure data integrity.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class VehicleDto {
    /**
     * The unique identifier for the vehicle.
     * This field is typically generated by the database.
     */
    private Long id;
    /**
     * The registration number of the vehicle.
     * This field is mandatory and cannot be blank.
     */
    @NotBlank(message = "Vehicle number cannot be empty.")
    private String vehicleNumber;
    /**
     * The type of the vehicle, such as CAR, BIKE, etc.
     * This is an enumerated type, defined in the VehicleType enum.
     */
    private VehicleType vehicleType;

}
