package com.fincons.parkingsystem.entity;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.SQLDelete;
import org.hibernate.annotations.Where;

/**
 * Represents a vehicle in the parking system.
 * This entity is mapped to the `vehicles` table in the database.
 * It includes a soft-delete mechanism, where records are marked as deleted
 * instead of being permanently removed.
 */
@Entity
@Table(name = "vehicles")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@SQLDelete(sql = "UPDATE vehicles SET deleted = true WHERE id=?")
@Where(clause = "deleted=false")
public class Vehicle {

    /**
     * The unique identifier for the vehicle.
     * This is the primary key and is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The registration number of the vehicle.
     * This is a unique and mandatory field.
     */
    @Column(nullable = false, unique = true)
    private String vehicleNumber;

    /**
     * The type of the vehicle, such as CAR, BIKE, etc.
     * This is an enumerated type and is stored as a string in the database.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private VehicleType vehicleType;

    /**
     * A flag to indicate whether the vehicle has been soft-deleted.
     * By default, this is `false`. When a vehicle is "deleted", this flag is set to `true`.
     */
    private boolean deleted = Boolean.FALSE;
}
